language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      # NOTE gcc-4.9 breaks clang
      - ubuntu-toolchain-r-test    # for gcc-4.8
      - llvm-toolchain-precise-3.7 # for clang
    packages:
      - clang
      - cmake
      - doxygen
      - g++-4.8
      - gcc-4.8
      - gettext
      - libbz2-dev
      - libgettextpo0
      - libgl1-mesa-dev
      - libirrlicht-dev
      - libjpeg8-dev
      - libleveldb-dev
      - libogg-dev
      - libopenal-dev
      - libpng12-dev
      - libsnappy-dev
      - libsqlite3-dev
      - libvorbis-dev
      - libxxf86vm-dev
      - llvm-3.7

before_install:
  - if [ $CC = 'gcc' ]; then
      export CC='gcc-4.8';
      export CXX='g++-4.8';
      export LINK='gcc-4.8';
      export LINKXX='g++-4.8';
    fi
  - if [ $TRAVIS_OS_NAME == 'osx' ]; then
      brew update;
      brew install gettext irrlicht libogg;
    fi
  - mkdir -p _build
  - cd _build
  #- git submodule update --init --recursive&

script:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      cmake -DENABLE_GETTEXT=1 ..;
      sudo make -j3 install;
    else
      cmake .. -DGETTEXT_LIBRARY=/usr/local/opt/gettext/lib/libgettextlib.dylib -DGETTEXT_INCLUDE_DIR=/usr/local/opt/gettext/include;
      make -j3 package;
    fi

notifications:
  email: false
